server:
  port: 80
  servlet:
    context-path: /api/web/v1
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  pattern:
    console: "%d{yy-MM-dd HH:mm:ss.SSS} [%15.15t] %-5p %-36.36c{36} - %msg%n"
  level:
    root: INFO
    demo: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: WARN
